name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build project
      working-directory: src
      run: dotnet build --configuration Release Markdig.SyntaxHighlighting.Core
    - name: Create the package
      working-directory: src
      run: dotnet pack --configuration Release Markdig.SyntaxHighlighting.Core
    - name: Publish the package to NuGet
      working-directory: src
      run: dotnet nuget push Markdig.SyntaxHighlighting.Core/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
